- name: varibles from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course infor
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}}, duration is {{DURATION}} and trainer is {{TRAINER}}"