- name: variables from inventory
  hosts: web
  tasks:
  - name: print the course details
    ansible.builtin.debug:
    msg: "i am learning {{COURSE}}, Duration is {{DURATION}} and Trainer is {{TRAINER}}"