- name: print the variables
  hosts: web
  # vars:
  #   COURSE: "Devops with aws from PLAY"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: COURSE
  #   prompt: please enter the course name
  #   private: false
  tasks:
  - name: print the variables
    # vars:
    #   COURSE: "DevOps with aws from task level"
    ansible.builtin.debug:
      msg: "i am learning {{COURSE}}"

# 1. first preference is command line or args.
# 2. second preference is task level.
# 3. the third preference is from vars file.
# 4. the fourth preference is from prompt.
# 5. the fifth preference is from Play level.
# 6. the Sixth preference is from inventory