- name: devops course information
  hosts: local
  connection: local ## you are in inside the ansible so it will search for username and pwd if you mention this
  vars:
    course: "devops with aws" #string
    duration: "120hrs" #number
    topics: #Lists
    - ansible
    - terraform
    - git
    - maven
    live: true #boolean
    tools: #map/dictionary
      ci: jenkin # string
      cm: ansible
      cloud:
      - aws
      - azure
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: " course name : {{course}}, duration is : {{duration}},topics are: {{topics}} live is {{live}}, tools are : {{tools}}"