- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check if expense user exist or not.
    ansible.builtin.command: id expense
    register: USER
    ignore_error: true

  - name: print the user info.
    ansible.builtin.debug:
      msg: "the user is: {{ USER }}"
