- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: print the facts
    ansible.builtin.debug:
      msg: "{{ansible_facts}}"
  
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"
  
  - name: Install nginx if Debian ## this will skip as we are not connected to debian
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"