- name: demo on filter/function
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "{{ COURSE | default('ansible')}}"

  - name: convert to upper case
    vars:
      greetings: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

  - name: convert to lowe case
    vars:
      greetings: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"

  - name: get the unique values
    vars:
      numbers: [1,2,4,3,5,5,6,3,4]
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

  - name: check if proper address or not
    vars: 
      myip: 198.165.3.4
    ansible.builtin.debug:
      msg: "{{myip | ansible.utils.ipaddr}}"
      
