- name: demo on filter/function
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "{{ COURSE | default('ansible')}}"

  - name: convert to upper case
    vars:
      greetings: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"
